// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttnnnqmxzrzworqqicql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0bm5ucW14enJ6d29ycXFpY3FsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NzM4NjAsImV4cCI6MjA3MTE0OTg2MH0.jTSRuVTvABP0Gb8M9pJwoJ8ADHe8y8TivwO_1JpZJ9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});